# Generated by Django 4.0.3 on 2022-08-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_person_myperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=60)),
            ],
        ),
    ]
